### PR TITLE
fix: regex correctly matches url() referenced assets

### PR DESCRIPTION
**Pull request by bsheen**
Additionally, adjusted how greedy the regex is and added
links out to Regex101.com for easy future reference

This fix addresses the issue reported here:
https://github.com/getgrav/grav-plugin-cdn/issues/7

### CODE REVIEW

**Comment by DanYoSon** [comment]
@bsheen I also ran into this issue. When looking at your PR I noticed the regex in your comment is slightly different than the actual code. In the comment you take into account both types of brackets `'` and `"`. Did you remove the double quotes for a reason?

**Comment by bsheen** [comment]
@DanYoSon it's most likely an oversight on my part. I think that double quotes should be included as per the comments and demonstrated here:
https://regex101.com/r/g0R6sj/3

**Comment by DanYoSon** [comment]
@bsheen I suspected that that was what happened. I just wanted to make sure I wasn't missing something and that there was something to learn :)

**Comment by rhukster** [comment]
Sorry it took so long.. fixed with double quote too.

**Comment by bsheen** [comment]
Thanks @rhukster!

**Pull request merged**
